account_info = [
    {
        'name': 'inc-prd-service',
        'alarm_sns': ['arn:aws:sns:ap-northeast-2:020953257447:standard-alertnow-sns'], 
        'event_sns': 'arn:aws:sns:ap-northeast-2:020953257447:standard-alertnow-sns',
        'assume_rolearn': 'arn:aws:iam::020953257447:role/airflow-alarm-automation',
        'event_rule_name' : 'alertnow-rule',
        'org': 'inc', 
        'env': 'prd',
        'alarm_period_1m': 60,
        'alarm_period_5m': 300,
        'alb_4xx_thres': 5,
        'alb_5xx_thres': 5,
        'alb_unhealthy_thres': 1,
        'nlb_unhealthy_thres': 1,
        'ec2_cpu_thres': 70,
        'ec2_mem_thres': 70,
        'ec2_disk_thres': 70,
        'rds_cpu_thres': 70,
        'rds_dbconn_thres': 70,
        'rds_freemem_thres': 10,
        'rds_volused_thres': 100000000000,
        'rds_freestor_thres': 20,
        'elasticache_cpu_thres': 70
    },
    {
        'name': 'inc-toolchain',
        'alarm_sns': ['arn:aws:sns:ap-northeast-2:755715193172:standard-alertnow-sns'], 
        'event_sns': 'arn:aws:sns:ap-northeast-2:755715193172:standard-alertnow-sns',
        'assume_rolearn': 'arn:aws:iam::755715193172:role/airflow-alarm-automation',
        'event_rule_name' : 'alertnow-rule',
        'org': 'inc', 
        'env': 'prd',
        'alarm_period_1m': 60,
        'alarm_period_5m': 300,
        'alb_4xx_thres': 5,
        'alb_5xx_thres': 5,
        'alb_unhealthy_thres': 1,
        'nlb_unhealthy_thres': 1,
        'ec2_cpu_thres': 70,
        'ec2_mem_thres': 70,
        'ec2_disk_thres': 70,
        'rds_cpu_thres': 70,
        'rds_dbconn_thres': 70,
        'rds_freemem_thres': 10,
        'rds_volused_thres': 100000000000,
        'rds_freestor_thres': 20,
        'elasticache_cpu_thres': 70
    },
    {
        'name': 'LogArchive',
        'alarm_sns': ['arn:aws:sns:ap-northeast-2:143304929087:standard-alertnow-sns'], 
        'event_sns': 'arn:aws:sns:ap-northeast-2:143304929087:standard-alertnow-sns',
        'assume_rolearn': 'arn:aws:iam::143304929087:role/airflow-alarm-automation',
        'event_rule_name' : 'alertnow-rule',
        'org': 'inc', 
        'env': 'prd',
        'alarm_period_1m': 60,
        'alarm_period_5m': 300,
        'alb_4xx_thres': 5,
        'alb_5xx_thres': 5,
        'alb_unhealthy_thres': 1,
        'nlb_unhealthy_thres': 1,
        'ec2_cpu_thres': 70,
        'ec2_mem_thres': 70,
        'ec2_disk_thres': 70,
        'rds_cpu_thres': 70,
        'rds_dbconn_thres': 70,
        'rds_freemem_thres': 10,
        'rds_volused_thres': 100000000000,
        'rds_freestor_thres': 20,
        'elasticache_cpu_thres': 70
    },
    {
        'name': 'inc-security',
        'alarm_sns': ['arn:aws:sns:ap-northeast-2:459171300478:standard-alertnow-sns'], 
        'event_sns': 'arn:aws:sns:ap-northeast-2:459171300478:standard-alertnow-sns',
        'assume_rolearn': 'arn:aws:iam::459171300478:role/airflow-alarm-automation',
        'event_rule_name' : 'alertnow-rule',
        'org': 'inc', 
        'env': 'prd',
        'alarm_period_1m': 60,
        'alarm_period_5m': 300,
        'alb_4xx_thres': 5,
        'alb_5xx_thres': 5,
        'alb_unhealthy_thres': 1,
        'nlb_unhealthy_thres': 1,
        'ec2_cpu_thres': 70,
        'ec2_mem_thres': 70,
        'ec2_disk_thres': 70,
        'rds_cpu_thres': 70,
        'rds_dbconn_thres': 70,
        'rds_freemem_thres': 10,
        'rds_volused_thres': 100000000000,
        'rds_freestor_thres': 20,
        'elasticache_cpu_thres': 70
    }
]
